name: gen
description: Content generator for Dart. For testing/mock propouse. **WIP**
version: 0.0.1+6
repository: https://github.com/enriquesaid/gen
homepage: https://github.com/enriquesaid/gen

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  strings: ^0.1.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
